config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  root 'homes#top'

  #非ログイン時TOP
  get 'homes/top'
 
  #ゲストログイン
  post '/homes/guest_user_sign_in', to: 'homes#new_guest_user'
  post '/homes/guest_shop_sign_in', to: 'homes#new_guest_shop'

  #管理者用デバイス
  devise_for :admins

  #会員用デバイス
  devise_for :users
  # omniauth_callbackコントローラーを介し、APIにリクエストを送る。
  devise_scope :user do
    #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2" => "users/omniauth_callbacks#passthru", as: :google_oauth
  end

  #店舗用デバイス
  devise_for :shops
  # devise_scope :shop do
  #   #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
  #   get "shops/auth/google_oauth2/callback" => "shops/omniauth_callbacks#google_oauth2"
  #   get "/auth/google_oauth2" => "shops/omniauth_callbacks#passthru", as: :shop_google_oauth
  # end

  #管理者用ルーティング 
  namespace :admins do
    get 'homes/top'

    resources :auto_mail_deliveries, only: [:index, :edit, :show, :update] do
      collection do
        get 'auto_mail_deliveries/form'
        post 'auto_mail_deliveries/confirm'
        post 'auto_mail_deliveries/completed'
      end
    end

    resources :news, only: [:index, :edit, :show, :update] do
      collection do
        get 'form'
        post 'confirm'
        post 'completed'
      end
    end

    resources :users, only: [:index, :edit, :show, :update] do
      collection do
        #検索用に追加
        get 'search'
      end
    end

    resources :shops, only: [:index, :edit, :show, :update] do
      collection do
        get 'search'
      end
    end

    resources :chat_rooms, only: [:index]

    resources :categories, only: [:index, :destroy] do
      collection do
        post 'g_category'
      end
    end

  end

  #店舗ルーティング 
  resources :shops, only: [:index, :edit, :show, :update] do
    resource :user_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #会員ルーティング 
  resources :users, only: [:index, :edit, :show, :update] do
    resource :shop_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #チャットルーティング 
  resources :chat_rooms, only: [:show, :create, :index]
  resources :chat_messages, only:[:create]

  resources :notifications, only:[:index]

  resources :news, only:[:index, :show]
  
  #問い合わせルーティング  
  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  # resources :chat_rooms, only: [:show, :create] do
  #   resources :chat_messages, only:[:create]
  # end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #アソシエーション
  belongs_to :category, optional: true
  has_many :user_followings, dependent: :destroy
  has_many :shop_followings, dependent: :destroy
  has_many :chat_rooms, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  
  #画像アップロード
  attachment :main_image
  attachment :sub_image
  attachment :appeal_image
  attachment :recommend_image
  
  #バリデーション
  validates :is_deleted,  inclusion: { in: [true, false]}

  with_options presence: true,on: :update do
    validates :name
    validates :name_kana
    validates :post_code
    validates :prefecture_code
    validates :city
    validates :block
    validates :building
    validates :phone_number
    validates :category_id
    validates :catchcopy
    #validates :main_image
    #validates :sub_image
    validates :appeal_text
    #validates :appeal_image
    validates :recommend_name
    validates :recommend_text
    #validates :recommend_image
  end

  validates :appeal_text, length: {maximum: 250}
  validates :recommend_name, length: {maximum: 15}
  validates :recommend_text, length: {maximum: 220}


  #jp_prefectureを使用したprefecture_codeからprefecture_nameへの変換
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  
  def address
    "%s %s %s"%([self.prefecture_name, self.city, self.block])
  end

  #adressを緯度経度に変換
  geocoded_by :address
  after_validation :geocode

  #お店がフォローしているユーザをすでフォローしているかしていないか
  def followed_by?(user)
    user_followings.where(user_id: user.id).exists?
  end

   # フォロー通知(shop→user)
   def create_notification_follow_user!(user)
    temp = Notification.where(["visiter_id = ? and visiter_type = ? and visited_id = ? and visited_type = ? and action = ? ", id, 'shop', user.id, 'user', 'follow'])
    # if temp.blank?
      notification = active_notifications.new(
        visiter_id: id,
        visiter_type: 'shop',
        visited_id: user.id,
        visited_type: 'user',
        action: 'follow'
      )
      notification.save if notification.valid?
    # end
  end

  #お店が退会している場合はログインを弾く
  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  #updateされたら新着に表示
  def updated?
    self.updated_at.between?(1.week.ago, Time.current)
  end

  protected
  # google認証
    def self.from_omniauth(access_token)
      data = access_token.info
      shop = Shop.where(email: data['email']).first

      # Uncomment the section below if you want shops to be created if they don't exist
      unless shop
        shop = Shop.create(email: data['email'],
          password: Devise.friendly_token[0,20]
        )
      end
      shop
    end
end

app/controllers/admins/shops_controller.rb
class Admins::ShopsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_shop, only: [:show, :edit, :update]

    def index
      @shops = Shop.all.order(id: "DESC").page(params[:page]).per(5)
      respond_to do |format|
        format.html
        format.csv do
          @shops = Shop.all
        end
      end
    end

    def show
        
    end

    def edit
        
    end

    def update
      if @shop.update(shop_params)
        redirect_to admins_shop_path(@shop)
      else
        render :edit
      end 
    end

    def search
        @content = params['content']
        @prefecture_code = params['prefecture_code']
        @category_ids = params['category_ids']
        @shops = search_shop(@content, @prefecture_code, @category_ids).page(params[:page]).per(5)
        respond_to do |format|
          format.html
          format.csv do
            @shops = search_shop(@content, @prefecture_code, @category_ids)
          end
        end
      end

    private

    def set_shop
      @shop = Shop.find(params[:id])
    end

    def shop_params
      params.require(:shop).permit(:name, :name_kana, :post_code, :prefecture_code, :city, :block, :building, :phone_number,:email, :category_id, :catchcopy, :main_image, :sub_image, :appeal_text, :appeal_image, :recommend_name, :recommend_text, :recommend_image, :is_deleted)
    end
    
    def search_shop(content, prefecture_code, category_ids)
      shops = Shop.all
      #「where!」で破壊的メソッドを利用して、present?でtrueの検索をして「return shops」で値を返す
        if content.present?
          shops.where!(['name LIKE ? OR name_kana LIKE ? OR catchcopy LIKE ?', "%#{content}%", "%#{content}%", "%#{content}%"])
        end
        if prefecture_code.present?
          shops.where!(prefecture_code: prefecture_code)
        end
        if category_ids.present?
          shops.where!(category_id: category_ids)
        end
      return shops
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_shop!, only: [:edit, :update, :withdraw]
  before_action :block_wrong_shop, only: [:edit, :update, :withdraw]
  before_action :set_shop, only: [:show, :edit, :update, :withdraw, :followers, :followings ]
  before_action :check_guest, only: [:update, :withdraw ]

  def show
    if @shop.is_deleted == false
      #ユーザが店舗詳細にてチャットを開始するため、ユーザがログインしていることが条件
      if user_signed_in?
        #お店と会員のチャットルームをeachで一つずつ取り出す
        current_user.chat_rooms.each do |cur|
          @shop.chat_rooms.each do |sr|
            #お店と会員のルームIDが等しければすでにルームは作成済みのため、@isRoom = trueとして@roomId = cur.idを代入
            if cur.id == sr.id
              @isRoom = true
              @roomId = cur.id
            end
          end
        end
        #@isRoomがfalse、つまりルームがなければインスタンス作成
        unless @isRoom
          @room = ChatRoom.new
        end
      end
    else
      flash[:notice] = "この店舗は退会しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      flash[:error] = "保存に失敗しました。"
      render :edit
    end
  end

  def index
    @shops= Shop.where(is_deleted: false).where.not(name: nil).page(params[:page]).per(5)
  end

  def search
    @content = params['content']
    @prefecture_code = params['prefecture_code']
    @category_ids = params['category_ids']
    @shops = search_shop(@content, @prefecture_code, @category_ids).where(is_deleted: false).where.not(name: nil).page(params[:page]).per(5)
  end

  def followers
    
  end

  def followings
    
  end

  def withdraw
    @shop.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end



  private
    def set_shop
      @shop = Shop.find(params[:id])
    end

    def block_wrong_shop
      if params[:id].to_i != current_shop.id
        flash[:alert] = "権限がありません"
        redirect_to root_path
      end
    end

    def check_guest
      @guest = Shop.find_by(email: 'guest@example.com')
      if current_shop == @guest
        flash[:alert] = "ゲストアカウントのため、変更や退会はお控えください"
        redirect_to root_path
      end
    end

    def shop_params
      params.require(:shop).permit(:name, :name_kana, :post_code, :prefecture_code, :city, :block, :building, :phone_number,:email, :category_id, :catchcopy, :main_image, :sub_image, :appeal_text, :appeal_image, :recommend_name, :recommend_text, :recommend_image, :is_deleted)
    end

    def search_shop(content, prefecture_code, category_ids)
      shops = Shop.where(is_deleted: false)
      #「where!」で破壊的メソッドを利用して、present?でtrueの検索をして「return shops」で値を返す
      if content.present?
        shops.where!(['name LIKE ? OR name_kana LIKE ? OR catchcopy LIKE ?', "%#{content}%", "%#{content}%", "%#{content}%"])
      end
      if prefecture_code.present?
        shops.where!(prefecture_code: prefecture_code)
      end
      if category_ids.present?
        shops.where!(category_id: category_ids)
      end
      return shops
    end

end

app/helpers/admins/shops_helper.rb
module Admins::ShopsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

end

app/views/shops/_follow_data.html.erb
フォロー数:<%= link_to shop.shop_followings.count, followings_shop_path(shop) %>
フォロワー数:<%= link_to shop.user_followings.count, followers_shop_path(shop) %>

app/views/shops/edit.html.erb
<div class="container">
    <div class ="row">
    <%= form_with model: @shop, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <div class="info1">
        <h3 class="heading">基本情報</h3>
            <table class="table">
              <tr>
                <td><%=  f.label :name, "店名" %></td>
                <td><%= f.text_field :name,  size: 35 %></td>
              </tr>
              <tr>
                <td><%=  f.label :name_kana, "カナ" %></td>
                <td><%= f.text_field :name_kana,  size: 35 %></td>
              </tr>
              <tr>
                <td><%=  f.label :phone_number, "TEL" %></td>
                <td><%= f.text_field :phone_number,  size: 35 %></td>
              </tr>
              <tr>
                <td>
                  <%=  f.label :category_id, "業種" %>
                  <br>
                  <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                    <img src="https://api.gnavi.co.jp/api/img/credit/api_155_20.gif" width="155" height="20" border="0" alt="グルメ情報検索サイト ぐるなび">
                  </a>
                </td>
                <td><%= f.select :category_id, Category.all.map{|category| [category.name, category.id]},  size: 35 %></td>
              </tr>
            </table>
            <p>住所</p>
            <table class="table">
              <tr>
                <td><%=  f.label :post_code, "郵便番号" %></td>
                <td><%= f.text_field :post_code, id:"address_zipcode",  size: 35 %></td>
              </tr>
              <tr>
                <td><%= f.label :prefecture_name, '都道府県' %></td>
                <td><%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, id: "prefecture_code",  size: 35 %></td>
              </tr>
              <tr>
                <td><%=  f.label :city, "市区町村" %></td>
                <td><%= f.text_field :city, id:"address_city",  size: 35 %></td>
              </tr>
              <tr>
                <td><%=  f.label :block, "番地" %></td>
                <td><%= f.text_field :block, id: "address_block",  size: 35 %></td>
              <tr>
                <td><%=  f.label :building, "建物" %></td>
                <td><%= f.text_field :building,  size: 35 %></td>
              </tr>
            </table>
        </div>
        <div class ="info2">
          <h3 class="heading">お店情報</h3>
          <table class="table">
            <tr>
            <td><%=  f.label :catchcopy, "キャッチコピー" %></td>
            <td><%= f.text_field :catchcopy ,  size: 35%></td>
            </tr>
          </table>
      <section class="shop-edit mv">
        <div class ="row">
          <div class ="col-sm-6">
            <h4><%=  f.label :main_image , "メインビジュアル" %></h4>
            <%= attachment_image_tag @shop, :main_image, class: "pre_image main_image", fallback: "no_image.svg"%>
            <%= f.attachment_field :main_image, placeholder: "画像", id: "main_image", class: "image_form" %>
          </div>
          <div class ="col-sm-6">
            <h4><%=  f.label :sub_image , "サブビジュアル" %></h4>
            <%= attachment_image_tag @shop, :sub_image, class: "pre_image sub_image", fallback: "no_image.svg"%>
            <%= f.attachment_field :sub_image, placeholder: "画像", id: "sub_image", class: "image_form" %>
          </div>
        </div>
      </section>
      
      <section class="shop-edit appeal">
        <h4><%=  f.label :appeal_image , "アピールポイント" %></h4>
        <div class ="row">
          <div class ="col-sm-6">
            <%= attachment_image_tag @shop, :appeal_image, class: "pre_image appeal_image", fallback: "no_image.svg" %>
            <%= f.attachment_field :appeal_image, placeholder: "画像", id: "appeal_image", class: "image_form" %>
          </div>
          <div class ="col-sm-6">
          <%= f.text_area :appeal_text, size: "70x10" %>
          <small>※250文字以内</small>
          </div>
        </div>
      </section>

      <section class="shop-edit recommend">
      <h4><%=  f.label :recommend_image , "お店のおすすめ！" %></h4>
        <div class ="row">
          <div class ="col-sm-6">
          <%= attachment_image_tag @shop, :recommend_image, class: "pre_image recommend_image", fallback: "no_image.svg" %>
          <%= f.attachment_field :recommend_image, placeholder: "画像", id: "recommend_image", class: "image_form" %>
          </div>
          <div class ="col-sm-6">
            <table class= "table">
              <tr>
                <td><h4><%=  f.label :recommend_name , "おすすめ商品" %></h4><br><small>※15文字以内</small></td>
                <td><%= f.text_field :recommend_name,  size: 40 %></td>
              </tr>
              <tr>
                <td><h4><%=  f.label :recommend_name , "おすすめ内容" %></h4><br><small>※220文字以内</small></td>
                <td><%= f.text_area :recommend_text,  size: "40x10" %></td>
              </tr>
            </table>
          </div>
        </div>
      </section>
      <div class ="shop-edit-action row justify-content-center">
        <%= f.submit "変更を保存する", class: "btn btn-primary" %>
      </div>
  <% end %>
    <div class= "row justify-content-end">
    <% if shop_signed_in? && @shop.id == current_shop.id %>
      <%= link_to "退会", withdraw_shop_path(current_shop), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-danger" %>
    <% end %>
  </div>
</div>





<!-- 画像プレビュー -->
<script>
$(function(){
  $('.image_form').on('change', function (e) {
    var reader = new FileReader();
    var form = $(this)
    reader.onload = function (e) {
      form.prevAll(".pre_image").attr('src', e.target.result);
    }  
    reader.readAsDataURL(e.target.files[0]);    
  });
});
</script>

<%# <script>
$(document).on('turbolinks:load', function() { 
  $('.image_form').on('click', function() {
      var image_id = $(this).attr('id');
      var image_class = $(this).prev('class');
      console.log(image_id);
      console.log(image_class);
  });
});
</script> %>

app/views/shops/followers.html.erb
<div class ="container">
    <div class= "row justify-content-center">
        <h2>フォロワー</h2>
    </div>
        <div class= "row justify-content-center">
            <div class ="col-sm-10">
                <div class= "main main-raised">
                    <table class="table table-striped" >
                        <% @shop.user_followings.each do |f| %>
                            <tr>
                                <td>
                                    <!-- 名前からroomの詳細に飛べるようにリンク化 -->
                                    <%= link_to user_path(f.user.id) do %>
                                        <%= attachment_image_tag f.user, :user_image, format: 'jpeg', class: "rounded-circle", fallback: "no_image.svg", size: "30x30" %>
                                        <%= f.user.full_name %>
                                    <% end %>
                                </td>
                                <td>
                                <span id="follow_<%= f.user.id %>" class="follow-btn">
                                    <%= render 'shop_followings/follow', user:f.user %>
                                </span>
                                </td>
                            </tr>
                        <% end %>
                    </table>
                </div>
            </div>
        </div>       
    </div>

app/views/shops/followings.html.erb
<div class ="container">
    <div class= "row justify-content-center">
        <h2>フォロー</h2>
    </div>
        <div class= "row justify-content-center">
            <div class ="col-sm-10">
                <div class= "main main-raised">
                    <table class="table table-striped" >
                        <% @shop.shop_followings.each do |f| %>
                            <tr>
                                <td>
                                    <!-- 名前からroomの詳細に飛べるようにリンク化 -->
                                    <%= link_to user_path(f.user.id) do %>
                                        <%= attachment_image_tag f.user, :user_image, format: 'jpeg', class: "rounded-circle", fallback: "no_image.svg", size: "30x30" %>
                                        <%= f.user.full_name %>
                                    <% end %>
                                </td>
                                <td>
                                <span id="follow_<%= f.user.id %>" class="follow-btn">
                                    <%= render 'shop_followings/follow', user:f.user %>
                                </span>
                                </td>
                            </tr>
                        <% end %>
                    </table>
                </div>
            </div>
        </div>       
    </div>

app/views/shops/index.html.erb
<div class="container">
    <div class ="col-sm-12">
    <div class ="form_box">
        <%= form_with url:search_shops_path, local: true, method: :post do |f| %>
            <div class="accordion" id="accordion-4">
                <div class="card">
                    <div class="card-header" id="header-4a">
                    <button class="btn btn-link" type="button"data-toggle="collapse" data-target="#card-4a" aria-expanded="true" aria-controls="card-4a">
                        業種
                    </button>
                    </div>
                    <div id="card-4a" class="collapse"aria-labelledby="header-4a" data-parent="#accordion-4">
                    <div class="card-body">
                        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, include_hidden: false) do |c| %>
                            <%= c.label class: 'form-check-label' do %>
                            <%= c.check_box class: 'form-check_input' %>
                            <%= c.text %>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="header-4b">
                    <button class="btn btn-link" type="button"data-toggle="collapse" data-target="#card-4b" aria-expanded="false" aria-controls="card-4b">
                        都道府県
                    </button>
                    </div>
                    <div id="card-4b" class="collapse"
                        aria-labelledby="header-4b" data-parent="#accordion-4">
                    <div class="card-body">
                        <%= f.collection_check_boxes(:prefecture_code, JpPrefecture::Prefecture.all, :code, :name, include_hidden: false) do |p| %>
                            <%= p.label class: 'form-check-label' do %>
                            <%= p.check_box class: 'form-check_input' %>
                            <%= p.text %>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
            </div>
            <div class ="form-content">
                <span class="form-content-label">フリーワード</span><%= f.text_field :content , class:"index-search" %>
            </div>
            <div class ="form-aciton">
                <%= f.submit "検索する" %>
            </div>
        <% end %>
    </div>
</div>
<!-- Page Content -->
    <div class="container">
        <% @shops.each do |shop| %>
        <div class= "row">
        <hr>
            <div class ="col-sm-6">
                <%= link_to shop_path(shop) do %>
                    <%= attachment_image_tag shop, :main_image, class: "index_main_image", fallback: "no_image.svg" %>
                <% end %>
            </div>
            <div class ="col-sm-6 index_info">
                <h3><%= shop.catchcopy %></h3>
                <table>
                <tr><h3>店名：<%= link_to shop.name, shop_path(shop) %></h3></tr>
                <tr>
                    地域：<%= shop.prefecture_name %>
                </tr>
                <tr>
                    業種：
                <% if shop.category_id.present? %>
                    <%= shop.category.name %>
                <% else %>
                未設定
                <% end %>
                </tr>
                <tr><h4>お店のアピールポイント</h4></tr>
                <tr>
                <div class="appeal_box">
                    <p class= "appeal_txet"><%= shop.appeal_text  %></p>
                </div>
                </tr>
                 <tr>
                    <span id="follow_<%= shop.id %>">
                        <%= render 'user_followings/follow', shop:shop %>
                    </span>
                </tr>
                </table>
            </div>
        </div>
        <hr>                 
        <% end %>
    </div>
<!-- Page Content -->
    <div class= "row justify-content-center">
        <%= paginate @shops %>
    </div>
 </div>

app/views/shops/show.html.erb
<% if @shop.is_deleted == false %>

<div class= "container">
    <h2 class="catch">
        <%= @shop.catchcopy %>
    </h2>
        <div class= "row">
            <div class ="col-sm-6">
                <div id="carouselControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <%= attachment_image_tag @shop, :main_image, class: "shop-show-iamge", fallback: "no_image.svg" %>
                        </div>
                        <div class="carousel-item">
                            <%= attachment_image_tag @shop, :sub_image, class: "shop-show-iamge", fallback: "no_image.svg" %>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </a>
                    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
            <div class ="col-sm-5 offset-1">
                <table >
                    <thead>
                        <td><h3><%= @shop.name %></h3></td>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <span id ="follow-count_<%= @shop.id %>">
                                <%= render 'shops/follow_data', shop:@shop %>
                            </span>
                        </td>
                    </tr>
                        <tr>
                            <td>業種</td>
                            <td>
                                <% if @shop.category_id.present? %>
                                <%= @shop.category.name %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <td>住所</td>
                            <td><%= @shop.address %></td>
                        </tr>
                        <tr>
                        <td>TEL</td>
                        <td><%= @shop.phone_number %></td>
                        </tr>
                        <tr>
                        <td colspan="2">
                            <div id="map"></div>
                        </td>
                        </tr>
                    </tbody>
                </table>
                <div class= "aciton-box">
                    <span id="follow_<%= @shop.id %>">
                        <%= render 'user_followings/follow', shop:@shop %>
                    </span>
                    <span id="chat_<%= @shop.id %>">
                        <%= render 'chat_rooms/shop_chat_button', shop:@shop %>
                    </span>
                    <% if @shop == current_shop %>
                      <%= link_to "編集する", edit_shop_path(@shop), class:"btn btn-primary" %>
                    <% end %>
                </div>
            </div>
        </div>
    <div class ="container">
    <div class= "row box_show">
        <div class ="col-sm-5 show_text">
            <h3 class="show_title">お店のアピールポイント</h3>
            <p><%= @shop.appeal_text  %></p>
        </div>
        <div class ="col-sm-6 offset-1 show-box-image">
            <%= attachment_image_tag @shop, :appeal_image, class: "show-image", fallback: "no_image.svg"  %>
        </div>
    </div>
    </div>

    <div class ="container">
    <div class= "row box_show">
        <div class ="col-sm-5 show_text">
            <h3 class="show_title" >お店のおすすめ！</h3>
                <h4><%= @shop.recommend_name %></h4>
                <p><%= @shop.recommend_text %></p>
        </div>
        <div class ="col-sm-6 offset-1 show-box-image">
            <%= attachment_image_tag @shop, :recommend_image, class: "show-image", fallback: "no_image.svg" %>
        </div>
    </div>
</div>
<% else %>
    <%= @shop.name %>は退会しました。
<% end %>


<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @shop.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>




<style type="text/css">
  #map { height: 200px;
         width: 100%;}
</style>