config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  root 'homes#top'

  #非ログイン時TOP
  get 'homes/top'
 
  #ゲストログイン
  post '/homes/guest_user_sign_in', to: 'homes#new_guest_user'
  post '/homes/guest_shop_sign_in', to: 'homes#new_guest_shop'

  #管理者用デバイス
  devise_for :admins

  #会員用デバイス
  devise_for :users
  # omniauth_callbackコントローラーを介し、APIにリクエストを送る。
  devise_scope :user do
    #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2" => "users/omniauth_callbacks#passthru", as: :google_oauth
  end

  #店舗用デバイス
  devise_for :shops
  # devise_scope :shop do
  #   #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
  #   get "shops/auth/google_oauth2/callback" => "shops/omniauth_callbacks#google_oauth2"
  #   get "/auth/google_oauth2" => "shops/omniauth_callbacks#passthru", as: :shop_google_oauth
  # end

  #管理者用ルーティング 
  namespace :admins do
    get 'homes/top'

    resources :auto_mail_deliveries, only: [:index, :edit, :show, :update] do
      collection do
        get 'auto_mail_deliveries/form'
        post 'auto_mail_deliveries/confirm'
        post 'auto_mail_deliveries/completed'
      end
    end

    resources :news, only: [:index, :edit, :show, :update] do
      collection do
        get 'form'
        post 'confirm'
        post 'completed'
      end
    end

    resources :users, only: [:index, :edit, :show, :update] do
      collection do
        #検索用に追加
        get 'search'
      end
    end

    resources :shops, only: [:index, :edit, :show, :update] do
      collection do
        get 'search'
      end
    end

    resources :chat_rooms, only: [:index]

    resources :categories, only: [:index, :destroy] do
      collection do
        post 'g_category'
      end
    end

  end

  #店舗ルーティング 
  resources :shops, only: [:index, :edit, :show, :update] do
    resource :user_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #会員ルーティング 
  resources :users, only: [:index, :edit, :show, :update] do
    resource :shop_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #チャットルーティング 
  resources :chat_rooms, only: [:show, :create, :index]
  resources :chat_messages, only:[:create]

  resources :notifications, only:[:index]

  resources :news, only:[:index, :show]
  
  #問い合わせルーティング  
  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  # resources :chat_rooms, only: [:show, :create] do
  #   resources :chat_messages, only:[:create]
  # end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
            <%= link_to inquiry_path do %>
              お問合せ<i class="far fa-envelope"></i>
            <% end %>
          </li>
          <% unless user_signed_in? or shop_signed_in? %>
          <li>
            <%= link_to 'ユーザーゲストログイン（閲覧用）', homes_guest_user_sign_in_path, method: :post %>
          </li>
          <li>
            <%= link_to 'お店ゲストログイン（閲覧用）', homes_guest_shop_sign_in_path, method: :post %>
          </li>
          <% end %>
        </ul>
      </nav>
      <div class="copyright float-right">
        ©︎musubu
      </div>
    </div>
  </footer>

app/views/shared/_header.html.erb
<header class="sticky-top js-header">  
    <nav class="navbar navbar-expand-lg">
        <%= link_to root_path, class:"navbar-brand"  do %>
            <% image_tag 'logo5.png', class:"logo logo-default" %>
        <% end %>
        <%= link_to root_path, class:"navbar-brand"  do %>
            <% image_tag 'logo6.png', class:"logo logo-scrolled" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <% if admin_signed_in? %>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item" >
                        <%= link_to  admins_homes_top_path, class:"nav-link" do %>
                            TOP<i class="fas fa-home"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to admins_shops_path, class:"nav-link" do %>
                            店舗一覧<i class="fas fa-store-alt"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  admins_users_path, class:"nav-link" do %>
                            ユーザ一覧<i class="fas fa-users"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  destroy_admin_session_path, method: :delete, class:"nav-link" do %>
                            ログアウト<i class="fas fa-door-open"></i>
                        <% end %>
                    </li>
                </ul>
            </div>
            <% elsif user_signed_in? %>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <%= link_to user_path(current_user.id), class:"nav-link" do %>
                            マイページ<i class="fas fa-home"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to chat_rooms_path, class:"nav-link" do %>
                            チャット<i class="far fa-envelope"></i>
                        <% end %>
                    </li>
                    <li class="nav-item notification">
                        <%= link_to notifications_path, class:"nav-link" do %>
                        通知<i class="fas fa-bell"></i>
                        <% end %>
                        <% if unchecked_notifications.any? %>
                            <span class="badge badge-warning notify-badge"><%= unchecked_count %></span>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  shops_path, class:"nav-link" do %>
                           お店を探す<i class="fas fa-store-alt"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to destroy_user_session_path, method: :delete, class:"nav-link"  do %>
                            ログアウト<i class="fas fa-door-open"></i>
                        <% end %>
                    </li>
                </ul>
            </div>
            <% elsif shop_signed_in? %>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <%= link_to  shop_path(current_shop.id), class:"nav-link" do %>
                            マイページ<i class="fas fa-home"></i>
                        <% end %>
                    </li>
                     <li class="nav-item">
                        <%= link_to chat_rooms_path, class:"nav-link" do %>
                            チャット<i class="far fa-envelope"></i>
                        <% end %>
                    </li>
                     <li class="nav-item notification">
                        <%= link_to notifications_path, class:"nav-link" do %>
                        通知<i class="fas fa-bell"></i>
                        <% end %>
                        <% if unchecked_notifications.any? %>
                            <span class="badge badge-warning notify-badge"><%= unchecked_count %></span>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to  users_path, class:"nav-link" do %>
                            後継者を探す<i class="fas fa-users"></i>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <%= link_to destroy_shop_session_path, method: :delete, class:"nav-link" do %>
                            ログアウト<i class="fas fa-door-open"></i>
                        <% end %>
                    </li>
                </ul>
            </div>
            <% else %>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown"><a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">ログイン</a>
                        <ul class="dropdown-menu">
                            <li class="nav-item"><%= link_to "会員の方", new_user_session_path  %></li>
                            <li class="nav-item"><%= link_to "お店の方", new_shop_session_path %></li>
                        </ul>
                        </li>
                        <li class="dropdown"><a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown">新規登録</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><%= link_to "会員の方", new_user_registration_path  %></li>
                                <li class="nav-item"><%= link_to "お店の方", new_shop_registration_path %></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            <% end %>
        </div>
    </nav>
</header>