config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  root 'homes#top'

  #非ログイン時TOP
  get 'homes/top'
 
  #ゲストログイン
  post '/homes/guest_user_sign_in', to: 'homes#new_guest_user'
  post '/homes/guest_shop_sign_in', to: 'homes#new_guest_shop'

  #管理者用デバイス
  devise_for :admins

  #会員用デバイス
  devise_for :users
  # omniauth_callbackコントローラーを介し、APIにリクエストを送る。
  devise_scope :user do
    #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2" => "users/omniauth_callbacks#passthru", as: :google_oauth
  end

  #店舗用デバイス
  devise_for :shops
  # devise_scope :shop do
  #   #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
  #   get "shops/auth/google_oauth2/callback" => "shops/omniauth_callbacks#google_oauth2"
  #   get "/auth/google_oauth2" => "shops/omniauth_callbacks#passthru", as: :shop_google_oauth
  # end

  #管理者用ルーティング 
  namespace :admins do
    get 'homes/top'

    resources :auto_mail_deliveries, only: [:index, :edit, :show, :update] do
      collection do
        get 'auto_mail_deliveries/form'
        post 'auto_mail_deliveries/confirm'
        post 'auto_mail_deliveries/completed'
      end
    end

    resources :news, only: [:index, :edit, :show, :update] do
      collection do
        get 'form'
        post 'confirm'
        post 'completed'
      end
    end

    resources :users, only: [:index, :edit, :show, :update] do
      collection do
        #検索用に追加
        get 'search'
      end
    end

    resources :shops, only: [:index, :edit, :show, :update] do
      collection do
        get 'search'
      end
    end

    resources :chat_rooms, only: [:index]

    resources :categories, only: [:index, :destroy] do
      collection do
        post 'g_category'
      end
    end

  end

  #店舗ルーティング 
  resources :shops, only: [:index, :edit, :show, :update] do
    resource :user_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #会員ルーティング 
  resources :users, only: [:index, :edit, :show, :update] do
    resource :shop_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #チャットルーティング 
  resources :chat_rooms, only: [:show, :create, :index]
  resources :chat_messages, only:[:create]

  resources :notifications, only:[:index]

  resources :news, only:[:index, :show]
  
  #問い合わせルーティング  
  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  # resources :chat_rooms, only: [:show, :create] do
  #   resources :chat_messages, only:[:create]
  # end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :edit, :update, :withdraw]

  def index
    @users = User.all.order(id: "DESC").page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.csv do
        @users = User.all
      end
    end
  end

  def show
        
  end

  def edit
        
  end

  def update
    if @user.update(user_params)
      redirect_to admins_user_path(@user)
    else
      render :edit
    end
  end

  def search
    @content = params['content']
    @prefecture_code = params['prefecture_code']
    @category_ids = params['category_ids']
    @users = search_user(@content, @prefecture_code, @category_ids).page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.csv do
        @users = search_user(@content, @prefecture_code, @category_ids)
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :prefecture_code, :phone_number, :email, :hope_prefecture_code, :category_id, :personality, :user_image, :pr, :is_deleted )
    end

    def search_user(content, prefecture_code, category_ids)
      users = User.all
        #「where!」で破壊的メソッドを利用して、present?でtrueの検索をして「return shops」で値を返す
        if content.present?
          users.where!(['first_name LIKE ? OR last_name LIKE ? OR first_name_kana LIKE ? OR last_name_kana LIKE ? OR pr LIKE ?', "%#{content}%", "%#{content}%", "%#{content}%", "%#{content}%", "%#{content}%"])
        end
        if prefecture_code.present?
          users.where!(hope_prefecture_code: prefecture_code)
        end
        if category_ids.present?
          users.where!(category_id: category_ids)
        end
      return users
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  def passthru
    binding.pry
    super
  end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  # def google_oauth2
  #  
  #   # You need to implement the method below in your model (e.g. app/models/user.rb)
  #   if  request.env["omniauth.params"]["type"] == "user"
  #     @user = User.from_omniauth(request.env['omniauth.auth'])
  #     if @user.persisted?
  #       flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
  #       sign_in_and_redirect @user, event: :authentication
  #     else
  #       session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
  #       redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
  #     end
  #   elsif request.env["omniauth.params"]["type"] == "shop"
  #     @shop = Shop.from_omniauth(request.env['omniauth.auth'])
  #     if @shop.persisted?
  #       flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
  #       sign_in_and_redirect @shop, event: :authentication
  #     else
  #       session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
  #       redirect_to new_shop_registration_url, alert: @shop.errors.full_messages.join("\n")
  #     end
  #   end
  # end

   def google_oauth2
    target_model, path = get_target_data
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    if target_model.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect target_model, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to path, alert: target_model.errors.full_messages.join("\n")
    end
   end

  private

    def get_target_data
      type = request.env["omniauth.params"]["type"]
      if type == "user"
        target_model = User.from_omniauth(request.env['omniauth.auth'])
        path = new_user_registration_url
      elsif type == "shop"
        target_model = Shop.from_omniauth(request.env['omniauth.auth'])
        path = new_shop_registration_url
      end
      return target_model, path
    end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :withdraw]
  before_action :block_wrong_user, only: [:edit, :update, :withdraw]
  before_action :set_user, only: [:show, :edit, :update, :withdraw, :followers, :followings ]
  before_action :check_guest, only: [:update, :withdraw ]

  def show
    if @user.is_deleted == false
      #店がユーザ詳細にてチャットを開始するため、店舗がログインしていることが条件
      if shop_signed_in?
        #お店と会員のチャットルームをeachで一つずつ取り出す
        current_shop.chat_rooms.each do |csr|
          @user.chat_rooms.each do |ur|
            #お店と会員のルームIDが等しければすでにルームは作成済みのため、@isRoom = trueとして@roomId = csr.idを代入
            if csr.id == ur.id
              @isRoom = true
              @roomId = csr.id
            end
          end
        end
        #@isRoomがfalse、つまりルームがなければインスタンス作成
        unless @isRoom
          @room = ChatRoom.new
        end
      end
    else
      flash[:notice] = "このユーザーは退会しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:error] = "保存に失敗しました。"
      render :edit
    end
  end

  def index
    @users = User.where(is_deleted: false).where.not(first_name: nil,last_name: nil ).page(params[:page]).per(5)
  end

 
  def search
    @content = params['content']
    @prefecture_code = params['prefecture_code']
    @category_ids = params['category_ids']
    @users = search_user(@content, @prefecture_code, @category_ids).where(is_deleted: false).where.not(first_name: nil,last_name: nil ).page(params[:page]).per(5)
  end

  def followers
    
  end

  def followings
    
  end

  def withdraw
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def block_wrong_user
      if params[:id].to_i != current_user.id
        flash[:alert] = "権限がありません"
        redirect_to root_path
      end
    end

    def check_guest
      @guest = User.find_by(email: 'guest@example.com')
      if current_user == @guest
        flash[:alert] = "ゲストアカウントのため、変更や退会はお控えください"
        redirect_to root_path
      end
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :prefecture_code, :phone_number, :email, :hope_prefecture_code, :category_id, :personality, :user_image, :pr )
    end

    def search_user(content, prefecture_code, category_ids)
      users = User.where(is_deleted: false)
      #「where!」で破壊的メソッドを利用して、present?でtrueの検索をして「return shops」で値を返す
      if content.present?
        users.where!(['first_name LIKE ? OR last_name LIKE ? OR first_name_kana LIKE ? OR last_name_kana LIKE ? OR pr LIKE ?', "%#{content}%", "%#{content}%", "%#{content}%", "%#{content}%", "%#{content}%"])
      end
      if prefecture_code.present?
        users.where!(hope_prefecture_code: prefecture_code)
      end
      if category_ids.present?
        users.where!(category_id: category_ids)
      end
      return users
    end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<div class= "container">
    <%= form_with model:[:admins,@user], local: true do |f| %>
        <div class= "row justify-content-center">
            <div class= "col-sm6">
                <%= attachment_image_tag @user, :user_image, class: "round_image", fallback: "no_image.svg", size:"300x300" %>
            </div>
        </div>
        <div class= "row justify-content-center">
            <div class= "col-sm-10">
                <div class= "main main-raised">
                    <table class="table table-borderless">
                        <tr>
                            <td></td>
                            <td><%= f.attachment_field :user_image, placeholder: "画像", id: "user_image" %></td>
                        </tr>
                        <tr>
                            <td><%= f.label :first_name, '氏名' %></td>
                            <td><%= f.text_field :last_name%><%= f.text_field :first_name %></td>
                        </tr>
                        <tr>
                            <td><%= f.label :first_name_kana, 'フリガナ' %></td>
                            <td><%= f.text_field :last_name_kana %><%=f.text_field :first_name_kana %></td>
                        </tr>
                        <tr>
                            <td><%= f.label :prefecture_name, 'お住まいの地域' %></td>
                            <td><%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, id: "user_prefecture_code"%></td>
                        </tr>
                        <tr>
                            <td><%= f.label :phone_number, '電話番号' %></td>
                            <td><%= f.telephone_field  :phone_number %></td>
                        </tr>
                        <tr>
                            <td><%= f.label :email, 'メールアドレス' %></td>
                            <td><%= f.email_field :email %></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td>
                                <%= f.label :personality, '個人' %><%= f.radio_button :personality, :true %>
                                <%= f.label :personality, '企業' %><%= f.radio_button :personality, :false %>
                            </td>
                        </tr>
                        <tr>
                            <td><%= f.label :category_id, '興味のある業種' %></td>
                            <td><%= f.select :category_id, Category.all.map{|category| [category.name, category.id]} %></td>
                            <!-- 都度APIを叩かずにcategoryモデルにAPIのデータを保存する方法に変更 -->
                            <% if false %>
                            <td><%= f.select :hope_category , @categories.map { |category| [category['category_l_name'], category['category_l_code']] } %></td>
                            <% end %>
                        </tr>
                        <tr>
                            <td><%= f.label :hope_prefecture_code, '希望地域' %></td>
                            <td><%= f.collection_select :hope_prefecture_code, JpPrefecture::Prefecture.all, :code, :name, id: "user_prefecture_code"%></td>
                        </tr>
                        <tr>
                            <td><%= f.label :pr, '自己PR' %></td>
                            <td><%= f.text_area :pr, size: "40x10" %></td>
                        </tr>
                        <tr>
                             <td><%= f.label :is_deleted, 'ステータス' %></td>
                            <td>                   
                                <span>有効</span><%= f.radio_button :is_deleted, :false %>
                                <span>退会済み</span><%= f.radio_button :is_deleted, :true %>
                             </td>
                        </tr>
                    </table>
                    <div class= "row justify-content-center">
                        <%= f.submit "変更を保存する", class: "btn btn-primary"%>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>




<!-- 画像プレビュー -->
<script>
$(function(){
    $('#user_image').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $(".round_image").attr('src', e.target.result);
}  
reader.readAsDataURL(e.target.files[0]);    
});
});
</script>

app/views/admins/users/index.html.erb
<div class="container">
    <div class ="col-sm-12">
    <div class ="form_box">
        <%= form_with url:search_admins_users_path, local: true, method: :get do |f| %>
            <div class="accordion" id="accordion-4">
                <div class="card">
                    <div class="card-header" id="header-4a">
                    <button class="btn btn-link" type="button"data-toggle="collapse" data-target="#card-4a" aria-expanded="true" aria-controls="card-4a">
                        業種
                    </button>
                    </div>
                    <div id="card-4a" class="collapse"aria-labelledby="header-4a" data-parent="#accordion-4">
                    <div class="card-body">
                        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, include_hidden: false) do |c| %>
                            <%= c.label class: 'form-check-label' do %>
                            <%= c.check_box class: 'form-check_input' %>
                            <%= c.text %>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="header-4b">
                    <button class="btn btn-link" type="button"data-toggle="collapse" data-target="#card-4b" aria-expanded="false" aria-controls="card-4b">
                        都道府県
                    </button>
                    </div>
                    <div id="card-4b" class="collapse"
                        aria-labelledby="header-4b" data-parent="#accordion-4">
                    <div class="card-body">
                        <%= f.collection_check_boxes(:prefecture_code, JpPrefecture::Prefecture.all, :code, :name, include_hidden: false) do |p| %>
                            <%= p.label class: 'form-check-label' do %>
                            <%= p.check_box class: 'form-check_input' %>
                            <%= p.text %>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
            </div>
            <div class ="form-content">
                <span class="form-content-label">フリーワード</span><%= f.text_field :content , class:"index-search" %>
            </div>
            <div class ="form-aciton">
                <%= f.submit "検索する" %>
            </div>
        <% end %>
    </div>
</div>
<div class="container">
    <%= link_to "CSV出力", admins_users_path(format: :csv), class: "btn btn-primary csv-btn" %>
</div>
 <div class="container">
    <% @users.each do |user| %>
    <div class= "row">
        <div class ="col-sm-5">
        <%= link_to admins_user_path(user) do %>
            <%= attachment_image_tag user, :user_image, class: "round_image  ", fallback: "no_image.svg", size:"300x300" %>
        <% end %>
        </div>
        <div class ="col-sm-7">
            <table>
            <tr>
                <% if user.full_name.present? %>
                    <h3><%= link_to user.full_name, admins_user_path(user) %></h3>
                <% else %>
                    <h3><%= link_to "NO NAME", admins_user_path(user) %></h3>
                <% end %>
            </tr>
            <tr>
            希望地域:<%= user.hope_prefecture_name %></tr>
            <br>
            <tr>希望業種:
                <% if user.category_id.present? %>
                    <%= user.category.name %></td>
                <% else %>
                    未設定
                <% end %>
            </tr>
            <tr>
                <h3>アピールポイント</h3>
            </tr>
            <tr>
            <div class="appeal_box">
                <p class= "appeal_txet"><%= user.pr  %></p>
            </div>
            </tr>
            <tr>
                <td>
                    <% if user.is_deleted == false %>
                        <span class= "btn btn-primary"><%= "有効" %></span>
                     <% else %> 
                        <span class= "btn btn-danger"><%= "無効" %></span>
                    <% end %>
                </td>
            </tr>
            </table>
        </div>
    </div>
    <hr>
    <% end %>
    <div class= "row justify-content-center">
        <%= paginate @users %>
    </div>
 </div>

app/views/admins/users/search.html.erb
<div class="container">
    <div class ="col-sm-12">
    <div class ="form_box">
        <%= form_with url:search_admins_users_path, local: true, method: :get do |f| %>
            <div class="accordion" id="accordion-4">
                <div class="card">
                    <div class="card-header" id="header-4a">
                    <button class="btn btn-link" type="button"data-toggle="collapse" data-target="#card-4a" aria-expanded="true" aria-controls="card-4a">
                        業種
                    </button>
                    </div>
                    <div id="card-4a" class="collapse"aria-labelledby="header-4a" data-parent="#accordion-4">
                    <div class="card-body">
                        <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name, include_hidden: false) do |c| %>
                            <%= c.label class: 'form-check-label' do %>
                            <%= c.check_box class: 'form-check_input' %>
                            <%= c.text %>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="header-4b">
                    <button class="btn btn-link" type="button"data-toggle="collapse" data-target="#card-4b" aria-expanded="false" aria-controls="card-4b">
                        都道府県
                    </button>
                    </div>
                    <div id="card-4b" class="collapse"
                        aria-labelledby="header-4b" data-parent="#accordion-4">
                    <div class="card-body">
                        <%= f.collection_check_boxes(:prefecture_code, JpPrefecture::Prefecture.all, :code, :name, include_hidden: false) do |p| %>
                            <%= p.label class: 'form-check-label' do %>
                            <%= p.check_box class: 'form-check_input' %>
                            <%= p.text %>
                            <% end %>
                        <% end %>
                    </div>
                    </div>
                </div>
            </div>
            <div class ="form-content">
                <span class="form-content-label">フリーワード</span><%= f.text_field :content , class:"index-search" %>
            </div>
            <div class ="form-aciton">
                <%= f.submit "検索する" %>
            </div>
        <% end %>
    </div>
    <div>
    </div>
    <div class="container">
        <%= link_to "CSV出力", search_admins_users_path(format: :csv, content: @content, prefecture_code: @prefecture_code, category_ids: @category_ids), class: "btn btn-primary csv-btn" %>
    </div>
</div>
 <div class="container">
    <% @users.each do |user| %>
    <div class= "row">
        <div class ="col-sm-5">
        <%= link_to admins_user_path(user) do %>
            <%= attachment_image_tag user, :user_image, class: "round_image  ", fallback: "no_image.svg", size:"300x300" %>
        <% end %>
        </div>
        <div class ="col-sm-7">
            <table>
            <tr>
                <% if user.full_name.present? %>
                    <h3><%= link_to user.full_name, admins_user_path(user) %></h3>
                <% else %>
                    <h3><%= link_to "NO NAME", admins_user_path(user) %></h3>
                <% end %>
            </tr>
            <tr>
            希望地域:<%= user.hope_prefecture_name %></tr>
            <br>
            <tr>希望業種:
                <% if user.category_id.present? %>
                    <%= user.category.name %></td>
                <% else %>
                    未設定
                <% end %>
            </tr>
            <tr>
                <h3>アピールポイント</h3>
            </tr>
            <tr>
            <div class="appeal_box">
                <p class= "appeal_txet"><%= user.pr  %></p>
            </div>
            </tr>
            <tr>
                <td>
                    <% if user.is_deleted == false %>
                        <span class= "btn btn-primary"><%= "有効" %></span>
                     <% else %> 
                        <span class= "btn btn-danger"><%= "無効" %></span>
                    <% end %>
                </td>
            </tr>
            </table>
        </div>
    </div>
    <hr>
    <% end %>
    <div class= "row justify-content-center">
        <%= paginate @users %>
    </div>
 </div>

app/views/admins/users/show.html.erb
<div class="container">
    <div class= "row justify-content-center">
        <div class ="col-sm6">
            <div class="profile-image-box">
                <%= attachment_image_tag @user, :user_image, class: "round_image", fallback: "no_image.svg", size:"300x300" %>
            </div>
         </div>
     </div>
    <div class= "row justify-content-center">
        <div class ="col-sm-10">
            <div class= "main main-raised">
                <table class="table table-borderless profile-info" >
                    <tr>
                        <td>
                            <span id ="follow-count_<%= @user.id %>">
                                <%= render 'users/follow_data', user:@user %>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>お名前:<%= @user.full_name %></td>
                    </tr>
                    <tr>
                        <td>フリガナ:<%= @user.full_name_kana %></td>
                    </tr>
                    <tr>
                        <td>住んでいる地域:<%=@user.prefecture_name %></td>
                    </tr>
                    <tr>
                        <td>希望地域:<%= @user.hope_prefecture_name %></td>
                    </tr>
                    <tr>
                        <td>
                            <% if @user.category_id.present? %>
                                希望業種:<%= @user.category.name %>
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <% if admin_signed_in? %>
                            <td colspan="2"><%= link_to "プロフィール編集", edit_admins_user_path(@user), class: "btn btn-primary" %></td>
                        <% end %>
                    </tr>
                </table>
                <div class= "row justify-content-center">
                    <div class= "profile-content">
                        <%= @user.pr %>
                    </div>
                </div>
                <div class= "row justify-content-center">
                    <% if @user.is_deleted == false %>
                        <span class= "btn btn-primary"><%= "有効" %></span>
                    <% else %> 
                        <span class= "btn btn-danger"><%= "無効" %></span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>