config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'
  root 'homes#top'

  #非ログイン時TOP
  get 'homes/top'
 
  #ゲストログイン
  post '/homes/guest_user_sign_in', to: 'homes#new_guest_user'
  post '/homes/guest_shop_sign_in', to: 'homes#new_guest_shop'

  #管理者用デバイス
  devise_for :admins

  #会員用デバイス
  devise_for :users
  # omniauth_callbackコントローラーを介し、APIにリクエストを送る。
  devise_scope :user do
    #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2/callback" => "users/omniauth_callbacks#google_oauth2"
    get "/auth/google_oauth2" => "users/omniauth_callbacks#passthru", as: :google_oauth
  end

  #店舗用デバイス
  devise_for :shops
  # devise_scope :shop do
  #   #get "/auth/:provider/callback" => "users/omniauth_callbacks#google_oauth2"
  #   get "shops/auth/google_oauth2/callback" => "shops/omniauth_callbacks#google_oauth2"
  #   get "/auth/google_oauth2" => "shops/omniauth_callbacks#passthru", as: :shop_google_oauth
  # end

  #管理者用ルーティング 
  namespace :admins do
    get 'homes/top'

    resources :auto_mail_deliveries, only: [:index, :edit, :show, :update] do
      collection do
        get 'auto_mail_deliveries/form'
        post 'auto_mail_deliveries/confirm'
        post 'auto_mail_deliveries/completed'
      end
    end

    resources :news, only: [:index, :edit, :show, :update] do
      collection do
        get 'form'
        post 'confirm'
        post 'completed'
      end
    end

    resources :users, only: [:index, :edit, :show, :update] do
      collection do
        #検索用に追加
        get 'search'
      end
    end

    resources :shops, only: [:index, :edit, :show, :update] do
      collection do
        get 'search'
      end
    end

    resources :chat_rooms, only: [:index]

    resources :categories, only: [:index, :destroy] do
      collection do
        post 'g_category'
      end
    end

  end

  #店舗ルーティング 
  resources :shops, only: [:index, :edit, :show, :update] do
    resource :user_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #会員ルーティング 
  resources :users, only: [:index, :edit, :show, :update] do
    resource :shop_followings, only: [:create, :destroy]
    member do
      put 'withdraw'
      get 'followings'
      get 'followers'
    end
    collection do
      #検索用に追加
      get 'search'
    end
  end

  #チャットルーティング 
  resources :chat_rooms, only: [:show, :create, :index]
  resources :chat_messages, only:[:create]

  resources :notifications, only:[:index]

  resources :news, only:[:index, :show]
  
  #問い合わせルーティング  
  get   'inquiry'         => 'inquiry#index'
  post  'inquiry/confirm' => 'inquiry#confirm'
  post  'inquiry/thanks'  => 'inquiry#thanks'

  # resources :chat_rooms, only: [:show, :create] do
  #   resources :chat_messages, only:[:create]
  # end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  #アソシエーション
  belongs_to :user
  belongs_to :shop
  has_many :chat_messages
  has_many :notifications, dependent: :destroy
  #バリデーション
  with_options presence: true do
    validates :user_id
    validates :shop_id
  end
end

app/controllers/admins/chat_rooms_controller.rb
class Admins::ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all.page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.csv do
        @chat_rooms = ChatRoom.all
      end
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :block_wrong_chat, only: [:show]
  def create
    #お店が作成した場合は、cuurent_shop.idとhiddenオプションで送られてきたuser_idを保存
    if shop_signed_in?
      @room = current_shop.chat_rooms.new(user_id: params[:user_id])
      @room.save
    #会員が作成した場合は、cuurent_user.idとhiddenオプションで送られてきたshop_idを保存
    elsif user_signed_in?
      @room = current_user.chat_rooms.new(shop_id: params[:shop_id])
      @room.save
    end
    redirect_to "/chat_rooms/#{@room.id}"
  end

  def show
    @room = ChatRoom.find(params[:id])
    @messages = @room.chat_messages.includes(:user).includes(:shop)
    @message = ChatMessage.new
    gon.skyway_key = ENV['SKYWAY_ID']
  end

  def index
    if shop_signed_in?
      @shop = current_shop
      @current_room = current_shop.chat_rooms
      myRoomIds = []
      @current_room.each do |chat_room|
        myRoomIds << chat_room.id
      end
      @shop_chat_rooms = ChatRoom.where(id: myRoomIds).order(created_at: :desc)
    elsif user_signed_in?
      @user = current_user
      @current_room = current_user.chat_rooms
      myRoomIds = []
      @current_room.each do |chat_room|
        myRoomIds << chat_room.id
      end
      @user_chat_rooms = ChatRoom.where(id: myRoomIds).order(created_at: :desc)
    end
  end

  private
    def block_wrong_chat
      chat_room = ChatRoom.find_by(id: params[:id])
      if user_signed_in?
        if chat_room.user_id != current_user.id
        flash[:alert] = "権限がありません"
        redirect_to root_path
        end
      elsif shop_signed_in?
        if chat_room.shop_id != current_shop.id
          flash[:alert] = "権限がありません"
          redirect_to root_path
        end
      elsif admin_signed_in?
        flash[:alert] = "管理者でログインしています"
      end

      unless user_signed_in? || shop_signed_in? || admin_signed_in?
        flash[:alert] = "ログインが必要です"
        redirect_to root_path
      end
    end


end

app/helpers/admins/chat_rooms_helper.rb
module Admins::ChatRoomsHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/admins/chat_rooms/index.html.erb
<div class= "container">
    <h2>チャット一覧</h2>
    <div>
        <%= link_to "CSV出力", admins_chat_rooms_path(format: :csv), class: "btn btn-primary csv-btn" %>
    </div>
    <table class="table table">
        <thead>
            <tr>
                <th>ID</th>
                <th>ユーザ</th>
                <th>お店</th>
                <th>更新日</th>
            </tr>
        </thead>
        <tbody>
            <% @chat_rooms.each do |cr| %>
                <tr>
                    <td>
                        <%= link_to cr.id, chat_room_path(cr.id), data: {"turbolinks" => false}  %>
                    </td>
                    <td>
                        <%= link_to admins_user_path(cr.user.id) do %>
                            <%= attachment_image_tag cr.user, :user_image, format: 'jpeg', class: "round_image", fallback: "no_image.svg", size: "30x30" %>
                            <%= cr.user.full_name %>
                        <% end %>
                    </td>
                    <td>
                        <%= link_to admins_shop_path(cr.shop.id) do %>
                            <%= attachment_image_tag cr.shop, :main_image, format: 'jpeg', class: "round_image", fallback: "no_image.svg", size: "30x30" %>
                            <%= cr.shop.name %>
                        <% end %>
                    </td>
                    <td><h6 style="color: #C0C0C0;"><%= cr.updated_at.strftime("%Y/%m/%d %H:%M") %></h6></td>
                </tr>
                <% end %>
        </tbody>
    </table>
    <div class= "row justify-content-center">
        <%= paginate @chat_rooms %>
    </div>
</div>